version: '3.7'
services:
  redis:
    image: redis/redis-stack:latest
    restart: unless-stopped
    ports:
      - 6379:6379  
      - 8001:8001   
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 2s
      timeout: 90s
      retries: 5
      start_period: 5s

volumes:
  redis-data:
    driver: local